CREATE TABLE PUBLIC.BATCH_REQUEST (
  BATCH_REQUEST_ID VARCHAR(100) NOT NULL,
  BATCH_REQUEST_NAME VARCHAR(100) NOT NULL,
  PROCESS_HALT_FLG CHAR(1) NOT NULL,
  PROCESS_ACTIVE_FLG CHAR(1) NOT NULL,
  SERVICE_AVAILABLE CHAR(1) NOT NULL,
  RESUME_POINT BIGINT NOT NULL,
  PRIMARY KEY (BATCH_REQUEST_ID)
);
COMMENT ON table PUBLIC.BATCH_REQUEST is 'バッチリクエスト';
COMMENT ON column PUBLIC.BATCH_REQUEST.BATCH_REQUEST_ID is 'バッチリクエストID';
COMMENT ON column PUBLIC.BATCH_REQUEST.BATCH_REQUEST_NAME is 'リクエスト名';
COMMENT ON column PUBLIC.BATCH_REQUEST.PROCESS_HALT_FLG is '処理停止フラグ';
COMMENT ON column PUBLIC.BATCH_REQUEST.PROCESS_ACTIVE_FLG is 'アクティブフラグ';
COMMENT ON column PUBLIC.BATCH_REQUEST.SERVICE_AVAILABLE is 'サービス提供可否状態';
COMMENT ON column PUBLIC.BATCH_REQUEST.RESUME_POINT is 'レジュームポイント';
CREATE TABLE PUBLIC.BUSINESS_DATE (
  SEGMENT_ID CHAR(2) NOT NULL,
  BIZ_DATE CHAR(8) NOT NULL,
  PRIMARY KEY (SEGMENT_ID)
);
COMMENT ON table PUBLIC.BUSINESS_DATE is '業務日付';
COMMENT ON column PUBLIC.BUSINESS_DATE.SEGMENT_ID is 'セグメントID';
COMMENT ON column PUBLIC.BUSINESS_DATE.BIZ_DATE is '業務日付';
CREATE TABLE PUBLIC.CODE_NAME (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG CHAR(2) NOT NULL,
  SORT_ORDER SMALLINT NOT NULL,
  CODE_NAME VARCHAR(50) NOT NULL,
  SHORT_NAME VARCHAR(50),
  OPTION01 VARCHAR(50),
  OPTION02 VARCHAR(50),
  OPTION03 VARCHAR(50),
  OPTION04 VARCHAR(50),
  OPTION05 VARCHAR(50),
  OPTION06 VARCHAR(50),
  OPTION07 VARCHAR(50),
  OPTION08 VARCHAR(50),
  OPTION09 VARCHAR(50),
  OPTION10 VARCHAR(50),
  PRIMARY KEY (CODE_ID, CODE_VALUE, LANG)
);
COMMENT ON table PUBLIC.CODE_NAME is 'コード名称';
COMMENT ON column PUBLIC.CODE_NAME.CODE_ID is 'コードID';
COMMENT ON column PUBLIC.CODE_NAME.CODE_VALUE is 'コード値';
COMMENT ON column PUBLIC.CODE_NAME.LANG is '言語';
COMMENT ON column PUBLIC.CODE_NAME.SORT_ORDER is 'ソート順';
COMMENT ON column PUBLIC.CODE_NAME.CODE_NAME is '名称';
COMMENT ON column PUBLIC.CODE_NAME.SHORT_NAME is 'コード略称';
COMMENT ON column PUBLIC.CODE_NAME.OPTION01 is 'オプション名称01';
COMMENT ON column PUBLIC.CODE_NAME.OPTION02 is 'オプション名称02';
COMMENT ON column PUBLIC.CODE_NAME.OPTION03 is 'オプション名称03';
COMMENT ON column PUBLIC.CODE_NAME.OPTION04 is 'オプション名称04';
COMMENT ON column PUBLIC.CODE_NAME.OPTION05 is 'オプション名称05';
COMMENT ON column PUBLIC.CODE_NAME.OPTION06 is 'オプション名称06';
COMMENT ON column PUBLIC.CODE_NAME.OPTION07 is 'オプション名称07';
COMMENT ON column PUBLIC.CODE_NAME.OPTION08 is 'オプション名称08';
COMMENT ON column PUBLIC.CODE_NAME.OPTION09 is 'オプション名称09';
COMMENT ON column PUBLIC.CODE_NAME.OPTION10 is 'オプション名称10';
CREATE TABLE PUBLIC.CODE_PATTERN (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  PATTERN01 CHAR(1) NOT NULL,
  PATTERN02 CHAR(1),
  PATTERN03 CHAR(1),
  PATTERN04 CHAR(1),
  PATTERN05 CHAR(1),
  PATTERN06 CHAR(1),
  PATTERN07 CHAR(1),
  PATTERN08 CHAR(1),
  PATTERN09 CHAR(1),
  PATTERN10 CHAR(1),
  PATTERN11 CHAR(1),
  PATTERN12 CHAR(1),
  PATTERN13 CHAR(1),
  PATTERN14 CHAR(1),
  PATTERN15 CHAR(1),
  PATTERN16 CHAR(1),
  PATTERN17 CHAR(1),
  PATTERN18 CHAR(1),
  PATTERN19 CHAR(1),
  PATTERN20 CHAR(1),
  PRIMARY KEY (CODE_ID, CODE_VALUE)
);
COMMENT ON table PUBLIC.CODE_PATTERN is 'コードパターン';
COMMENT ON column PUBLIC.CODE_PATTERN.CODE_ID is 'コードID';
COMMENT ON column PUBLIC.CODE_PATTERN.CODE_VALUE is 'コード値';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN01 is 'パターン01';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN02 is 'パターン02';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN03 is 'パターン03';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN04 is 'パターン04';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN05 is 'パターン05';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN06 is 'パターン06';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN07 is 'パターン07';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN08 is 'パターン08';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN09 is 'パターン09';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN10 is 'パターン10';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN11 is 'パターン11';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN12 is 'パターン12';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN13 is 'パターン13';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN14 is 'パターン14';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN15 is 'パターン15';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN16 is 'パターン16';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN17 is 'パターン17';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN18 is 'パターン18';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN19 is 'パターン19';
COMMENT ON column PUBLIC.CODE_PATTERN.PATTERN20 is 'パターン20';
CREATE TABLE PUBLIC.MAIL_ATTACHED_FILE (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER NUMERIC(10) NOT NULL,
  FILE_NAME VARCHAR(150) NOT NULL,
  CONTENT_TYPE VARCHAR(50) NOT NULL,
  ATTACHED_FILE BYTEA NOT NULL,
  PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER)
);
COMMENT ON table PUBLIC.MAIL_ATTACHED_FILE is 'メール添付ファイル';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.SERIAL_NUMBER is '連番';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.FILE_NAME is '添付ファイル名';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.CONTENT_TYPE is '添付ファイルCONTENT-TYPE';
COMMENT ON column PUBLIC.MAIL_ATTACHED_FILE.ATTACHED_FILE is '添付ファイル';
CREATE TABLE PUBLIC.MAIL_RECIPIENT (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER BIGINT NOT NULL,
  RECIPIENT_TYPE CHAR(1) NOT NULL,
  MAIL_ADDRESS VARCHAR(254) NOT NULL,
  PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER)
);
COMMENT ON table PUBLIC.MAIL_RECIPIENT is 'メール送信先';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.SERIAL_NUMBER is '連番';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.RECIPIENT_TYPE is '送信先区分';
COMMENT ON column PUBLIC.MAIL_RECIPIENT.MAIL_ADDRESS is 'メールアドレス';
CREATE TABLE PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  MAIL_SEND_PATTERN_ID VARCHAR(2),
  SUBJECT VARCHAR(150) NOT NULL,
  MAIL_BODY VARCHAR(4000) NOT NULL,
  MAIL_FROM VARCHAR(254) NOT NULL,
  REPLY_TO VARCHAR(254) NOT NULL,
  RETURN_PATH VARCHAR(254) NOT NULL,
  CHARSET VARCHAR(50) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  REQUEST_DATETIME TIMESTAMP,
  SEND_DATETIME TIMESTAMP,
  PROCESS_ID CHAR(36),
  PRIMARY KEY (MAIL_REQUEST_ID)
);
COMMENT ON table PUBLIC.MAIL_REQUEST is 'メール送信要求';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_SEND_PATTERN_ID is 'メール送信パターンID';
COMMENT ON column PUBLIC.MAIL_REQUEST.SUBJECT is '件名';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_BODY is '本文';
COMMENT ON column PUBLIC.MAIL_REQUEST.MAIL_FROM is '送信者メールアドレス';
COMMENT ON column PUBLIC.MAIL_REQUEST.REPLY_TO is '返信先メールアドレス';
COMMENT ON column PUBLIC.MAIL_REQUEST.RETURN_PATH is '差戻し先メールアドレス';
COMMENT ON column PUBLIC.MAIL_REQUEST.CHARSET is '文字セット';
COMMENT ON column PUBLIC.MAIL_REQUEST.STATUS is 'ステータス';
COMMENT ON column PUBLIC.MAIL_REQUEST.REQUEST_DATETIME is '要求日時';
COMMENT ON column PUBLIC.MAIL_REQUEST.SEND_DATETIME is '送信日時';
COMMENT ON column PUBLIC.MAIL_REQUEST.PROCESS_ID is 'プロセスID';
CREATE TABLE PUBLIC.MAIL_TEMPLATE (
  MAIL_TEMPLATE_ID VARCHAR(10) NOT NULL,
  LANG CHAR(2) NOT NULL,
  SUBJECT VARCHAR(150) NOT NULL,
  MAIL_BODY TEXT NOT NULL,
  CHARSET VARCHAR(50) NOT NULL,
  PRIMARY KEY (MAIL_TEMPLATE_ID, LANG)
);
COMMENT ON table PUBLIC.MAIL_TEMPLATE is 'メールテンプレート';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.MAIL_TEMPLATE_ID is 'メールテンプレートID';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.LANG is '言語';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.SUBJECT is '件名';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.MAIL_BODY is '本文';
COMMENT ON column PUBLIC.MAIL_TEMPLATE.CHARSET is '文字セット';
CREATE TABLE PUBLIC.SAMPLE_USER (
  USER_INFO_ID CHAR(20) NOT NULL,
  LOGIN_ID VARCHAR(20) NOT NULL,
  KANJI_NAME VARCHAR(50) NOT NULL,
  KANA_NAME VARCHAR(50) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  PRIMARY KEY (USER_INFO_ID)
);
COMMENT ON table PUBLIC.SAMPLE_USER is 'サンプルユーザ情報';
COMMENT ON column PUBLIC.SAMPLE_USER.USER_INFO_ID is 'ユーザ情報ID';
COMMENT ON column PUBLIC.SAMPLE_USER.LOGIN_ID is 'ログインID';
COMMENT ON column PUBLIC.SAMPLE_USER.KANJI_NAME is '漢字氏名';
COMMENT ON column PUBLIC.SAMPLE_USER.KANA_NAME is 'かな氏名';
COMMENT ON column PUBLIC.SAMPLE_USER.STATUS is '処理ステータス';
ALTER TABLE PUBLIC.CODE_NAME
ADD
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES PUBLIC.CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);
ALTER TABLE PUBLIC.MAIL_ATTACHED_FILE
ADD
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID
);
ALTER TABLE PUBLIC.MAIL_RECIPIENT
ADD
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES PUBLIC.MAIL_REQUEST (
  MAIL_REQUEST_ID
);

